### PR TITLE
Calculates the mean in quantiles.py

### PR DESCRIPTION
**Pull request by jrising**
This adds a column 'mean' by default, which calculates the mean of the same distribution that the quantiles are normally calculated from.  You can override that by changing the `evalqvals` configuration option (now default: `['mean', .17, .5, .83]`).

### CODE REVIEW

**Comment by jrising** [comment]
Can you test this out?

**Comment by trinetta** [comment]
sure! will test it out and get back to you asap

**Comment by jrising** [comment]
I'm merging it in to master now!

**Comment by trinetta** [comment]
great! thank you James!

**Pull request merged**
