### PR TITLE
List regions when reporting all regions

### PR DESCRIPTION
**Pull request by jrising**
This is in response to @trinetta's request last Thursday.

### CODE REVIEW

**Comment by jrising** [comment]
@trinetta I tested this, but it's always good to have someone else check it with their own process.  Can you tell me if this is what you needed when getting all region data out?

**Comment by trinetta** [comment]
will test it out! get back to you as soon as I can

**Comment by trinetta** [comment]
@jrising Just tested out the listreg branch! It seems to be working well:

```
trinetta@sacagawea:/shares/gcp/social/parameters/mortality/mortality_nonFGLS-TINV_CYA_NW_diffclip30_210918/montecarlos$ head rcp85-SSP2_montecarlos_high_fulladapt_valuescsv_impact_map.csv
region,year,batch,gcm,iam,value,weight
CAN.1.2.28,1981,batch5,CanESM2,high,0.000392029,0.03
CAN.1.17.403,1981,batch5,CanESM2,high,0.00031327,0.03
CAN.2.34.951,1981,batch5,CanESM2,high,0.000109981,0.03
CAN.11.259.4274,1981,batch5,CanESM2,high,0.000236919,0.03
CAN.11.269.4448,1981,batch5,CanESM2,high,0.000382331,0.03
CAN.2.34.941,1981,batch5,CanESM2,high,7.22015e-05,0.03
CAN.8.117.2357,1981,batch5,CanESM2,high,0.000263743,0.03
CAN.6.98.2246,1981,batch5,CanESM2,high,0.00104777,0.03
CAN.8.118.2365,1981,batch5,CanESM2,high,0.000423108,0.03
````

**Comment by jrising** [comment]
Thanks for checking!

**Pull request merged**
